In [1]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt # 학습 결과 플롯용 패키지
from sklearn import datasets

boston = datasets.load_boston()
boston_slice = [x[5] for x in boston.data] # 6번째 피쳐만 사용




In [2]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
boston_slice

[6.575,
 6.421,
 7.185,
 6.998,
 7.147,
 6.43,
 6.012,
 6.172,
 5.631,
 6.004,
 6.377,
 6.009,
 5.889,
 5.949,
 6.096,
 5.834,
 5.935,
 5.99,
 5.456,
 5.727,
 5.57,
 5.965,
 6.142,
 5.813,
 5.924,
 5.599,
 5.813,
 6.047,
 6.495,
 6.674,
 5.713,
 6.072,
 5.95,
 5.701,
 6.096,
 5.933,
 5.841,
 5.85,
 5.966,
 6.595,
 7.024,
 6.77,
 6.169,
 6.211,
 6.069,
 5.682,
 5.786,
 6.03,
 5.399,
 5.602,
 5.963,
 6.115,
 6.511,
 5.998,
 5.888,
 7.249,
 6.383,
 6.816,
 6.145,
 5.927,
 5.741,
 5.966,
 6.456,
 6.762,
 7.104,
 6.29,
 5.787,
 5.878,
 5.594,
 5.885,
 6.417,
 5.961,
 6.065,
 6.245,
 6.273,
 6.286,
 6.279,
 6.14,
 6.232,
 5.874,
 6.727,
 6.619,
 6.302,
 6.167,
 6.389,
 6.63,
 6.015,
 6.121,
 7.007,
 7.079,
 6.417,
 6.405,
 6.442,
 6.211,
 6.249,
 6.625,
 6.163,
 8.069,
 7.82,
 7.416,
 6.727,
 6.781,
 6.405,
 6.137,
 6.167,
 5.851,
 5.836,
 6.127,
 6.474,
 6.229,
 6.195,
 6.715,
 5.913,
 6.092,
 6.254,
 5.928,
 6.176,
 6.021,
 5.872,
 5.731,
 5.87,
 6.004,
 5.961,
 5.856,
 5.879,
 5.986,
 5.6

In [4]:
np.array(boston_slice)

array([6.575, 6.421, 7.185, 6.998, 7.147, 6.43 , 6.012, 6.172, 5.631,
       6.004, 6.377, 6.009, 5.889, 5.949, 6.096, 5.834, 5.935, 5.99 ,
       5.456, 5.727, 5.57 , 5.965, 6.142, 5.813, 5.924, 5.599, 5.813,
       6.047, 6.495, 6.674, 5.713, 6.072, 5.95 , 5.701, 6.096, 5.933,
       5.841, 5.85 , 5.966, 6.595, 7.024, 6.77 , 6.169, 6.211, 6.069,
       5.682, 5.786, 6.03 , 5.399, 5.602, 5.963, 6.115, 6.511, 5.998,
       5.888, 7.249, 6.383, 6.816, 6.145, 5.927, 5.741, 5.966, 6.456,
       6.762, 7.104, 6.29 , 5.787, 5.878, 5.594, 5.885, 6.417, 5.961,
       6.065, 6.245, 6.273, 6.286, 6.279, 6.14 , 6.232, 5.874, 6.727,
       6.619, 6.302, 6.167, 6.389, 6.63 , 6.015, 6.121, 7.007, 7.079,
       6.417, 6.405, 6.442, 6.211, 6.249, 6.625, 6.163, 8.069, 7.82 ,
       7.416, 6.727, 6.781, 6.405, 6.137, 6.167, 5.851, 5.836, 6.127,
       6.474, 6.229, 6.195, 6.715, 5.913, 6.092, 6.254, 5.928, 6.176,
       6.021, 5.872, 5.731, 5.87 , 6.004, 5.961, 5.856, 5.879, 5.986,
       5.613, 5.693,

In [5]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:

#텐서플로에서 사용할 크기로 조정
# reshape 함수로 데이터를 열이 1인 배열형으로 변환
data_x = np.array(boston_slice).reshape(-1,1)
data_y = boston.target.reshape(-1,1)

In [7]:
data_x

array([[6.575],
       [6.421],
       [7.185],
       [6.998],
       [7.147],
       [6.43 ],
       [6.012],
       [6.172],
       [5.631],
       [6.004],
       [6.377],
       [6.009],
       [5.889],
       [5.949],
       [6.096],
       [5.834],
       [5.935],
       [5.99 ],
       [5.456],
       [5.727],
       [5.57 ],
       [5.965],
       [6.142],
       [5.813],
       [5.924],
       [5.599],
       [5.813],
       [6.047],
       [6.495],
       [6.674],
       [5.713],
       [6.072],
       [5.95 ],
       [5.701],
       [6.096],
       [5.933],
       [5.841],
       [5.85 ],
       [5.966],
       [6.595],
       [7.024],
       [6.77 ],
       [6.169],
       [6.211],
       [6.069],
       [5.682],
       [5.786],
       [6.03 ],
       [5.399],
       [5.602],
       [5.963],
       [6.115],
       [6.511],
       [5.998],
       [5.888],
       [7.249],
       [6.383],
       [6.816],
       [6.145],
       [5.927],
       [5.741],
       [5.966],
       [

In [8]:
data_y

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [9]:
print(data_x.shape, data_y.shape)

(506, 1) (506, 1)


In [10]:
#선형회귀는 y = wx+b로 입력데이터x * 기울기(w)+편향(b)= 타깃데이터(y)가 되는 기울기, 편향을 찾는것이 목표
#입력데이터 X의 크기는 샘플 수 X 피쳐수가 되고 타깃 데이터의 크기는 샘플 수 X1이 됨
#이를 바탕으로 입출력에 필요한 플레이스홀더와 변수를 정의

#입력 데이터의 샘플 수를 얻는다
n_sample = data_x.shape[0]

In [11]:
#샘플 수 X 피쳐 수의 플레이스홀더, 피쳐를 하나만 사용하므로 피쳐 수는 1이 됨
X = tf.placeholder(tf.float32, shape=(n_sample,1),name = 'X')
#샘플 수 X 타깃 수의 플레이스홀더, 타깃수가 집값하나 이므로 1
y = tf.placeholder(tf.float32, shape=(n_sample,1), name= 'y')

#기울기, 피쳐 수 X 타깃 수의 크기를 가집니다. 피쳐 수와 타깃 수가 1이므로 기울기는 1X1로 정의
W = tf.Variable(tf.zeros((1,1)),name='weights')
#편향, 타깃 수 X 타깃 수의 크기를 가집니다. 타깃 수가 1이므로 기울기는 1X1로 정의
b = tf.Variable(tf.zeros((1,1)), name='bias')


In [12]:
#학습함수, 손실함수, 최적화함수 정의
#입력데이터와 기울기의 곱을 구하기 위해 matmul, 제곱값을 사용하기 위해 square, 제곱손실값을 더한 뒤 평균을 내기 위해 reduce_mean을 사용
y_pred = tf.matmul(X,W) + b
loss = tf.reduce_mean(tf.square(y_pred - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train_op = optimizer.minimize(loss)
summary_op = tf.summary.scalar('loss',loss)

In [13]:
def plot_graph(y, fout):
    '''데이터 플롯을 위한 함수. 입력값(피처값), 출력값(집값)을 플롯합니다.'''
    
    plt.scatter(data_x.reshape(1,-1)[0], boston.target.reshape(1,-1)[0])
    plt.plot(data_x.reshape(1,-1)[0],y.reshape(1,-1)[0])
    plt.savefig(fout)
    plt.clf()

with tf.Session() as sess:
    #코드안에서 세션을 정의
    sess.run(tf.global_variables_initializer())# 변수 초기화
    
    #텐서보드용 서머리 라이터를 위에서 지정한 디렉터리와 그래프를 이용하여 생성
    summary_writer = tf.summary.FileWriter('./graphs',sess.graph)
    
    #학습전의 예측된 기울기 상태
    y_pred_before = sess.run(y_pred, {X: data_x})
    
    plot_graph(y_pred_before,'before.png')
    
    #최적화 함수를 이용하여 기울기를 100번 업데이트
    for i in range(100):
        #loss 연산, summary_op 연산, train_op 연산을 수행한다.
        #loss 연산의 결과를 loss_t, summary_op 연산의 결과를 summary에 받습니다.
        loss_t, summary, _ = sess.run([loss, summary_op, train_op], feed_dict={X:data_x, y:data_y})
        
        #각 업데이트 마다 생성된 summary_op 함수의 결과를 서머리 라이터에 적습니다.
        summary_writer.add_summary(summary, i)
        
        if i %10 == 0:
            print('loss=% 4.4f' % loss_t.mean()) #10회 학습 후의 평균손실
            y_pred_after = sess.run(y_pred, {X:data_x})
            
    y_pred_after= sess.run(y_pred, {X: data_x})
    plot_graph(y_pred_after, 'after.png')

loss= 592.1469
loss= 155.3169
loss= 76.3167
loss= 62.0246
loss= 59.4341
loss= 58.9596
loss= 58.8678
loss= 58.8452
loss= 58.8351
loss= 58.8273


<Figure size 432x288 with 0 Axes>